name: Waka Readme

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # tiap hari 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # ==== CONFIG FLAGS (di sini) ====
          LOCALE: "en"
          SECTION_NAME: "waka"              # cocok dengan START_SECTION:waka
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"

          COMMIT_MESSAGE: "Updated with Dev Metrics"
          COMMIT_BY_ME: "False"             # kalau True, isi COMMIT_EMAIL/USERNAME sesuai kamu
          COMMIT_USERNAME: "readme-bot"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
